In [1]:
from fin_statement_model.importers.fmp import FMPAdapter

# Example usage
api_key = "4A7zLDw1zxKtZn3eVlFN3ZHGbLXpGKz3"
period = "annual"
ticker = "AAPL"

In [2]:
adapter = FMPAdapter(api_key)
fsg = adapter.create_income_statement_graph(ticker, period=period)

In [3]:
fsg.add_metric("net_income")
fsg.add_metric("ebit")
fsg.add_metric("ebitda")

In [6]:
fsg.to_dataframe()

,FY2020,FY2021,FY2022,FY2023,FY2024
revenue,2.745150e+11,3.658170e+11,3.943280e+11,3.832850e+11,3.910350e+11
cost_of_goods_sold,1.695590e+11,2.129810e+11,2.235460e+11,2.141370e+11,2.103520e+11
research_and_development_expenses,1.875200e+10,2.191400e+10,2.625100e+10,2.991500e+10,3.137000e+10
general_and_administrative_expenses,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
selling_and_marketing_expenses,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
selling_general_and_administrative_expenses,1.991600e+10,2.197300e+10,2.509400e+10,2.493200e+10,2.609700e+10
other_interest_expenses,8.700000e+07,-6.000000e+07,2.280000e+08,3.820000e+08,0.000000e+00
interest_income,3.763000e+09,2.843000e+09,2.825000e+09,3.750000e+09,0.000000e+00
interest_expense,2.873000e+09,2.645000e+09,2.931000e+09,3.933000e+09,0.000000e+00
tax_expense,9.680000e+09,1.452700e+10,1.930000e+10,1.674100e+10,2.974900e+10
depreciation_and_amortization,1.105600e+10,1.128400e+10,1.110400e+10,1.151900e+10,1.144500e+10
operating_expenses,3.866800e+10,4.388700e+10,5.134500e+10,5.484700e+10,5.746700e+10
gross_profit,1.049560e+11,1.528360e+11,1.707820e+11,1.691480e+11,1.806830e+11
operating_income,6.628800e+10,1.089490e+11,1.194370e+11,1.143010e+11,1.232160e+11
total_interest_expense,8.030000e+08,2.580000e+08,-3.340000e+08,-5.650000e+08,0.000000e+00
pre_tax_income,6.709100e+10,1.092070e+11,1.191030e+11,1.137360e+11,1.232160e+11
net_income,5.741100e+10,9.468000e+10,9.980300e+10,9.699500e+10,9.346700e+10
ebit,6.628800e+10,1.089490e+11,1.194370e+11,1.143010e+11,1.232160e+11
ebitda,7.734400e+10,1.202330e+11,1.305410e+11,1.258200e+11,1.346610e+11

In [5]:
print(fsg)

Financial Statement Graph Summary
========================================

Periods: FY2020, FY2021, FY2022, FY2023, FY2024

Financial Statement Items:
-------------------------
• revenue
• cost_of_goods_sold
• research_and_development_expenses
• general_and_administrative_expenses
• selling_and_marketing_expenses
• selling_general_and_administrative_expenses
• other_interest_expenses
• interest_income
• interest_expense
• tax_expense
• depreciation_and_amortization

Calculations:
-------------------------
• operating_expenses = f(research_and_development_expenses, general_and_administrative_expenses, selling_and_marketing_expenses, selling_general_and_administrative_expenses)

Metrics:
-------------------------
• ebit
• ebitda
• gross_profit
• net_income
• operating_income
• pre_tax_income
• total_interest_expense

Forecasted Items:
-------------------------